import { useMemo, useState } from 'react'
import { createFixtureStore } from '../lib/store/fixtureStore'
import type { PermissionMode } from '../../shared/types'

type View = 'overview' | 'field' | 'patterns' | 'opportunities' | 'memory' | 'activity' | 'report'

const nav: { id: View; label: string; hint: string }[] = [
  { id: 'overview', label: 'Domain brief', hint: 'Context and constraints' }, { id: 'field', label: 'Project field', hint: 'Items and signals' }, { id: 'patterns', label: 'Patterns', hint: 'Clusters and gaps' }, { id: 'opportunities', label: 'Opportunities', hint: 'What to do next' }, { id: 'memory', label: 'Memory', hint: 'Review proposed changes' }, { id: 'activity', label: 'Activity', hint: 'Visible agent trail' }, { id: 'report', label: 'Field report', hint: 'Synthesis' },
]
const fixtureStore = createFixtureStore()
const allThingsAgentic = fixtureStore.domains[0]
const { actors, items, opportunities, patterns, signals, memory: demoMemory } = fixtureStore

export function App() {
  const [view, setView] = useState<View>('overview')
  const [mode, setMode] = useState<PermissionMode>('observe')
  const [interests, setInterests] = useState('trustworthy agents, evaluation, learning from builders')
  const [memoryStatus, setMemoryStatus] = useState(demoMemory[2].status)
  const acceptedMemory = useMemo(() => demoMemory.filter((entry) => entry.status === 'accepted' || (entry.id === 'memory-proposed' && memoryStatus === 'accepted')), [memoryStatus])

  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">◎</span><span>Signal Scout</span></div><p className="eyebrow">HACKATHON SCOUT</p><div className="domain-card"><strong>{allThingsAgentic.name}</strong><span>Seed field loaded</span><small>{items.length} projects · {signals.length} signals</small></div><nav>{nav.map((item) => <button key={item.id} className={view === item.id ? 'nav-item active' : 'nav-item'} onClick={() => setView(item.id)}><span>{item.label}</span><small>{item.hint}</small></button>)}</nav><div className="sidebar-footer"><span className="status-dot" /> Local mock mode<br /><small>Ready for review</small></div></aside>
    <main className="main"><header className="topbar"><div><p className="eyebrow">DISCOVERY WORKSPACE / {view.toUpperCase()}</p><h1>{nav.find((item) => item.id === view)?.label}</h1></div><label className="mode-select">Agent mode <select value={mode} onChange={(event) => setMode(event.target.value as PermissionMode)}><option value="observe">Observe</option><option value="suggest">Suggest</option><option value="act_with_approval">Act with approval</option></select></label></header><section className="content">{view === 'overview' && <Overview interests={interests} setInterests={setInterests} setView={setView} mode={mode} />}{view === 'field' && <Field />}{view === 'patterns' && <Patterns />}{view === 'opportunities' && <Opportunities />}{view === 'memory' && <Memory status={memoryStatus} setStatus={setMemoryStatus} />}{view === 'activity' && <Activity />}{view === 'report' && <Report acceptedMemory={acceptedMemory.length} />}</section></main>
  </div>
}

function Overview({ interests, setInterests, setView, mode }: { interests: string; setInterests: (value: string) => void; setView: (view: View) => void; mode: PermissionMode }) { return <><div className="hero"><div><span className="pill">{mode.replace('_', ' ')}</span><h2>Find what the field is trying to teach you.</h2><p>{allThingsAgentic.summary}</p></div><div className="hero-orbit">◎<span>explore<br />extract<br />cluster<br />plan</span></div></div><div className="grid two"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">YOUR CONTEXT</p><h3>What are you curious about?</h3></div><span className="count">01</span></div><textarea value={interests} onChange={(event) => setInterests(event.target.value)} /><button className="primary" onClick={() => setView('field')}>Start scouting <span>→</span></button></article><article className="panel"><p className="eyebrow">EVENT BRIEF</p><h3>Strategic constraints</h3><ul className="clean-list">{allThingsAgentic.constraints.map((item) => <li key={item}><span>↳</span>{item}</li>)}</ul><div className="criteria"><strong>Judging for</strong>{allThingsAgentic.judgingCriteria.map((item) => <span key={item}>{item}</span>)}</div></article></div><div className="stats"><div><strong>03</strong><span>projects scanned</span></div><div><strong>05</strong><span>signals extracted</span></div><div><strong>02</strong><span>patterns mapped</span></div><div><strong>03</strong><span>next moves</span></div></div></> }
function Field() { return <><div className="section-intro"><p>Three projects give us a compact, readable field to learn from. Relevance is based on your stated interests.</p><span className="pill">observe · source-backed</span></div><div className="project-grid">{items.map((item) => <article className="project-card" key={item.id}><div className="card-top"><span className="tag">{item.maturity}</span><span className="relevance">{item.relevance}% match</span></div><h3>{item.title}</h3><p>{item.summary}</p><div className="stack">{item.stack.map((tech) => <span key={tech}>{tech}</span>)}</div><footer><span>{actors.find((actor) => actor.id === item.actorIds[0])?.name}</span><button onClick={() => undefined}>Inspect signal →</button></footer></article>)}</div></> }
function Patterns() { return <div className="stack-layout">{patterns.map((pattern, index) => <article className="pattern-row" key={pattern.id}><span className="pattern-number">0{index + 1}</span><div><div className="card-top"><span className="tag">{pattern.confidence} confidence</span><span className="muted">{pattern.signalIds.length} linked signals</span></div><h2>{pattern.name}</h2><p>{pattern.summary}</p><div className="gap"><strong>Whitespace</strong>{pattern.gap}</div></div></article>)}</div> }
function Opportunities() { return <div className="stack-layout">{opportunities.map((opportunity) => <article className="opportunity-row" key={opportunity.id}><span className="opportunity-icon">{opportunity.kind === 'build' ? '↗' : opportunity.kind === 'learn' ? '✦' : '⌁'}</span><div><div className="card-top"><span className="tag">{opportunity.kind}</span><span className="muted">{opportunity.confidence} confidence</span></div><h2>{opportunity.title}</h2><p>{opportunity.explanation}</p><small><strong>Why now:</strong> {opportunity.whyNow}</small></div><button className="save-button">Save</button></article>)}</div> }
function Memory({ status, setStatus }: { status: string; setStatus: (status: 'accepted' | 'rejected' | 'proposed') => void }) { return <div className="memory-layout"><div><p className="section-lead">Memory is user-owned. Nothing proposed here is saved without your review.</p>{demoMemory.map((entry) => <article className="memory-card" key={entry.id}><div><span className="tag">{entry.category}</span><p>{entry.text}</p></div><span className={entry.id === 'memory-proposed' ? `memory-status ${status}` : 'memory-status accepted'}>{entry.id === 'memory-proposed' ? status : entry.status}</span>{entry.id === 'memory-proposed' && status === 'proposed' && <div className="memory-actions"><button onClick={() => setStatus('accepted')}>Accept</button><button onClick={() => setStatus('rejected')}>Reject</button></div>}</article>)}</div><aside className="review-note"><span className="eyebrow">REVIEW POLICY</span><h3>Inspect before remembering</h3><p>Signal Scout can suggest a useful preference or reflection, but the decision stays with you.</p></aside></div> }
function Activity() { return <div className="activity-list"><div className="activity-header"><p className="section-lead">Every route leaves a visible trail. This demo is running without network access.</p><span className="pill">4 events</span></div>{['Loaded All Things Agentic seed field', 'Extracted 5 source-backed signals', 'Mapped 2 patterns and 3 opportunities', 'Proposed one memory update for review'].map((message, index) => <article className="activity-event" key={message}><span className="timeline-dot" /><div><div className="card-top"><strong>{index === 0 ? 'intake' : index === 1 ? 'itemScout' : index === 2 ? 'patternMap' : 'memoryReview'}</strong><span className="muted">just now</span></div><p>{message}</p><small>permission: {index === 3 ? 'suggest' : 'observe'} · status: completed</small></div></article>)}</div> }
function Report({ acceptedMemory }: { acceptedMemory: number }) { return <article className="report"><div className="report-cover"><p className="eyebrow">SIGNAL SCOUT / FIELD REPORT</p><h2>What the agentic field is teaching us</h2><p>{allThingsAgentic.name} · generated from {items.length} projects, {signals.length} signals, and {patterns.length} patterns</p></div><div className="report-section"><span className="eyebrow">EXECUTIVE SIGNAL</span><h3>Inspectable autonomy is the opening.</h3><p>The strongest projects make agent behavior legible through evidence, evaluation, and meaningful human checkpoints. A builder-focused field report can turn those patterns into a clear learning loop.</p></div><div className="report-columns"><div><span className="eyebrow">TOP PATTERNS</span>{patterns.map((pattern) => <p key={pattern.id}><strong>{pattern.name}</strong><br />{pattern.summary}</p>)}</div><div><span className="eyebrow">NEXT MOVES</span>{opportunities.map((opportunity) => <p key={opportunity.id}><strong>{opportunity.title}</strong><br />{opportunity.explanation}</p>)}</div></div><div className="report-footer">{acceptedMemory} memory entries accepted · activity trail complete · mock mode</div></article> }
