import { useState, useSyncExternalStore } from 'react'
import type { PermissionMode } from '../../shared/types'
import { MockAgent } from '../services/agent'
import { createAppStore } from '../lib/store/createStore'
import { selectActivityTasks, selectApprovalQueue, selectDomain, selectPendingApprovals, selectPendingMemory, selectSavedOpportunities } from '../lib/store/selectors'
import { getRoutePermission } from '../lib/permissions/permissionState'
import { LiveWorkspace } from './LiveWorkspace'
import type { LiveWorkspaceSummary } from './livePresentation'

type View = 'overview' | 'field' | 'patterns' | 'opportunities' | 'memory' | 'activity' | 'report'
type ExecutionMode = 'mock' | 'live'
const nav: { id: View; label: string; hint: string }[] = [
  { id: 'overview', label: 'Domain brief', hint: 'Context and constraints' }, { id: 'field', label: 'Project field', hint: 'Items and signals' }, { id: 'patterns', label: 'Findings', hint: 'Requirements and strategic gaps' }, { id: 'opportunities', label: 'Opportunities', hint: 'What to do next' }, { id: 'memory', label: 'Memory', hint: 'Review proposed changes' }, { id: 'activity', label: 'Activity', hint: 'Visible agent trail' }, { id: 'report', label: 'Field report', hint: 'Synthesis' },
]

const appStore = createAppStore()
const agent = new MockAgent(appStore)

export function App() {
  const state = useSyncExternalStore(appStore.subscribe, appStore.getState, appStore.getState)
  const [view, setView] = useState<View>('overview')
  const [mode, setMode] = useState<PermissionMode>('observe')
  const [executionMode, setExecutionMode] = useState<ExecutionMode>('mock')
  const [liveSummary, setLiveSummary] = useState<LiveWorkspaceSummary>({ title: 'Public hackathon scan', detail: 'Ready for public input' })
  const [interests, setInterests] = useState('trustworthy agents, evaluation, learning from builders')
  const domain = selectDomain(state)

  const runWorkflow = () => { agent.runScoutingWorkflow(interests, mode); setView('activity') }
  const reviewMemory = (memoryId: string, status: 'accepted' | 'rejected') => agent.reviewMemory(memoryId, status)
  const saveOpportunity = (opportunityId: string) => agent.saveOpportunity(opportunityId)

  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">◎</span><span>Signal Scout</span></div><p className="eyebrow">HACKATHON SCOUT</p><div className="domain-card"><strong>{executionMode === 'mock' ? domain?.name : liveSummary.title}</strong><span>{executionMode === 'mock' ? 'SYNTHETIC FIXTURE · LOCAL MOCK' : 'LIVE API · REAL PUBLIC INPUT'}</span><small>{executionMode === 'mock' ? `${state.items.length} demo-only projects · ${state.signals.length} synthetic signals` : liveSummary.detail}</small></div><nav>{nav.map((item) => <button key={item.id} className={view === item.id ? 'nav-item active' : 'nav-item'} onClick={() => setView(item.id)}><span>{item.label}</span><small>{item.hint}</small></button>)}</nav><div className="sidebar-footer">{executionMode === 'mock' ? <><span className="status-dot" /> {state.tasks.length} mock activity record{state.tasks.length === 1 ? '' : 's'}<br /><small>{selectPendingMemory(state).length} memory review item{selectPendingMemory(state).length === 1 ? '' : 's'} · {selectPendingApprovals(state).length} approval{selectPendingApprovals(state).length === 1 ? '' : 's'} pending</small><button className="reset-button" onClick={() => { appStore.reset(); setView('overview') }}>Reset demo</button></> : <><span className="status-dot" /> Live execution mode<br /><small>Only backend results are shown</small></>}</div></aside>
    <main className="main"><header className="topbar"><div><p className="eyebrow">DISCOVERY WORKSPACE / {view.toUpperCase()}</p><h1>{nav.find((item) => item.id === view)?.label}</h1></div><div className="mode-controls"><label className="mode-select">Execution <select value={executionMode} onChange={(event) => { setExecutionMode(event.target.value as ExecutionMode); setView('overview') }}><option value="mock">Mock demo</option><option value="live">Live scan</option></select></label>{executionMode === 'mock' && <label className="mode-select">Mock permission intent <select value={mode} onChange={(event) => setMode(event.target.value as PermissionMode)}><option value="observe">Observe</option><option value="suggest">Suggest</option><option value="act_with_approval">Act with approval</option></select></label>}</div></header><section className="content">{executionMode === 'live' ? <LiveWorkspace view={view} onNavigate={setView} onSummaryChange={setLiveSummary} /> : <>{view === 'overview' && <Overview domain={domain} interests={interests} setInterests={setInterests} onStart={runWorkflow} mode={mode} nextMoves={state.opportunities.length} />}{view === 'field' && <Field state={state} onStart={runWorkflow} />}{view === 'patterns' && <Patterns state={state} />}{view === 'opportunities' && <Opportunities state={state} onSave={saveOpportunity} />}{view === 'memory' && <Memory state={state} onReview={reviewMemory} />}{view === 'activity' && <Activity state={state} />}{view === 'report' && <Report state={state} onGenerate={() => { agent.runFieldReport('suggest') }} />}</>}</section></main>
  </div>
}

function Overview({ domain, interests, setInterests, onStart, mode, nextMoves }: { domain: ReturnType<typeof selectDomain>; interests: string; setInterests: (value: string) => void; onStart: () => void; mode: PermissionMode; nextMoves: number }) { return <><div className="hero"><div><span className="pill">{mode.replace('_', ' ')}</span><h2>Find what the field is trying to teach you.</h2><p>{domain?.summary}</p></div><div className="hero-orbit">◎<span>explore<br />extract<br />compare<br />plan</span></div></div><div className="grid two"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">YOUR CONTEXT</p><h3>What are you curious about?</h3></div><span className="count">01</span></div><textarea value={interests} onChange={(event) => setInterests(event.target.value)} /><button className="primary" onClick={onStart}>Run mock scout <span>→</span></button></article><article className="panel"><p className="eyebrow">EVENT BRIEF</p><h3>Strategic constraints</h3><ul className="clean-list">{domain?.constraints.map((item) => <li key={item}><span>↳</span>{item}</li>)}</ul><div className="criteria"><strong>Judging for</strong>{domain?.judgingCriteria.map((item) => <span key={item}>{item}</span>)}</div></article></div><div className="stats"><div><strong>03</strong><span>projects in field</span></div><div><strong>05</strong><span>signals available</span></div><div><strong>02</strong><span>findings mapped</span></div><div><strong>{nextMoves}</strong><span>next moves</span></div></div></> }

function Field({ state, onStart }: { state: ReturnType<typeof appStore.getState>; onStart: () => void }) { const lowConfidenceSignals = state.signals.filter((signal) => signal.confidence === 'low'); return <><div className="section-intro"><p>All projects, people, scores, signals, and findings here are deterministic synthetic fixtures for tests and offline UI development. They are not real participants or field research. {lowConfidenceSignals.length > 0 ? `${lowConfidenceSignals.length} synthetic signal${lowConfidenceSignals.length === 1 ? '' : 's'} use low confidence.` : ''}</p><button className="primary" onClick={onStart}>Run mock field analysis →</button></div><div className="project-grid">{state.items.map((item) => <article className="project-card" key={item.id}><div className="card-top"><span className="tag">{item.maturity}</span><span className="relevance">deterministic demo score: {item.relevance}%</span></div><h3>{item.title}</h3><p>{item.summary}</p><div className="stack">{item.stack.map((tech) => <span key={tech}>{tech}</span>)}</div><footer><span>{state.actors.find((actor) => actor.id === item.actorIds[0])?.name}</span><span>{item.signalIds.length} synthetic signals linked</span></footer></article>)}</div><div className="stack-layout"><p className="eyebrow">SYNTHETIC SIGNAL CONFIDENCE</p>{state.signals.map((signal) => <article className="signal-card" key={signal.id}><span className="tag">{signal.confidence}</span><div><strong>{signal.title}</strong><p>{signal.observation}</p></div></article>)}</div></> }
function Patterns({ state }: { state: ReturnType<typeof appStore.getState> }) { return <div className="stack-layout">{state.patterns.map((pattern, index) => <article className="pattern-row" key={pattern.id}><span className="pattern-number">0{index + 1}</span><div><div className="card-top"><span className="tag">{pattern.confidence} confidence</span><span className="muted">{pattern.signalIds.length} linked signals</span></div><h2>{pattern.name}</h2><p>{pattern.summary}</p><div className="gap"><strong>Whitespace</strong>{pattern.gap}</div></div></article>)}</div> }
function Opportunities({ state, onSave }: { state: ReturnType<typeof appStore.getState>; onSave: (opportunityId: string) => void }) { return <div className="stack-layout">{state.opportunities.map((opportunity) => <article className="opportunity-row" key={opportunity.id}><span className="opportunity-icon">{opportunity.kind === 'build' ? '↗' : opportunity.kind === 'learn' ? '✦' : '⌁'}</span><div><div className="card-top"><span className="tag">{opportunity.kind}</span><span className="muted">{opportunity.confidence} confidence</span></div><h2>{opportunity.title}</h2><p>{opportunity.explanation}</p><small><strong>Why now:</strong> {opportunity.whyNow}</small></div><button className="save-button" disabled={opportunity.status === 'saved'} onClick={() => onSave(opportunity.id)}>{opportunity.status === 'saved' ? 'Saved' : 'Save'}</button></article>)}</div> }
function Memory({ state, onReview }: { state: ReturnType<typeof appStore.getState>; onReview: (memoryId: string, status: 'accepted' | 'rejected') => void }) { return <div className="memory-layout"><div><p className="section-lead">Concept memory is stored only in this browser's local mock state. Nothing proposed here changes a Live project or account.</p>{state.memory.map((entry) => { const approval = state.approvals.find((candidate) => candidate.relatedMemoryId === entry.id); return <article className="memory-card" key={entry.id}><div><span className="tag">{entry.category}</span><p>{entry.text}</p></div><span className={`memory-status ${entry.status}`}>{entry.status}</span>{entry.status === 'proposed' && <div className="memory-actions"><small>{approval?.status === 'pending' ? 'Concept approval required before changing local mock state' : 'Concept review complete'}</small><button onClick={() => onReview(entry.id, 'accepted')}>Accept in mock</button><button onClick={() => onReview(entry.id, 'rejected')}>Reject in mock</button></div>}</article>})}</div><aside className="review-note"><span className="eyebrow">CONCEPT / MOCK REVIEW POLICY</span><h3>Inspect before remembering</h3><p>This demonstrates a possible user-controlled memory review. The current action changes only the local synthetic fixture.</p></aside></div> }
function Activity({ state }: { state: ReturnType<typeof appStore.getState> }) { const tasks = selectActivityTasks(state); const pendingApproval = selectPendingApprovals(state).length; const approvals = selectApprovalQueue(state); return <div className="activity-list"><div className="activity-header"><p className="section-lead">Every mock route leaves a visible local trail. {tasks.length} task record{tasks.length === 1 ? '' : 's'} {tasks.length === 1 ? 'is' : 'are'} stored in this browser's fixture state. {pendingApproval > 0 ? `${pendingApproval} concept approval${pendingApproval === 1 ? '' : 's'} ${pendingApproval === 1 ? 'still needs' : 'still need'} review.` : 'No concept approvals are waiting.'}</p><span className="pill">{tasks.length} mock task{tasks.length === 1 ? '' : 's'}</span></div>{approvals.map((approval) => <article className="review-note" key={approval.id}><span className="eyebrow">CONCEPT APPROVAL / {approval.scope}</span><h3>{approval.status === 'pending' ? 'Pending concept review' : `Concept decision recorded: ${approval.status}`}</h3><p>{approval.reason}</p><small>{approval.action} · requested {approval.requestedAt} · local mock only</small></article>)}{tasks.map((task) => <article className="activity-event" key={task.id}><span className="timeline-dot" /><div><div className="card-top"><strong>{task.route}</strong><span className="muted">{task.status} · {getRoutePermission(task.route, task.permissionMode).decision}</span></div><p>{task.title}</p>{task.events.map((event) => <small key={event.id}>{event.kind === 'fallback' ? 'Fallback: ' : ''}{event.message}<br /></small>)}</div></article>)}</div> }
function Report({ state, onGenerate }: { state: ReturnType<typeof appStore.getState>; onGenerate: () => void }) { const report = state.report; return <article className="report"><div className="report-cover"><p className="eyebrow">SIGNAL SCOUT / FIELD REPORT</p><h2>{report?.title ?? 'Your report is waiting for a run'}</h2><p>{report ? `Generated ${new Date(report.generatedAt).toLocaleTimeString()} from the current structured state.` : 'Run the mock scout from the Domain Brief to generate this structured artifact.'}</p></div>{report ? <><div className="report-section"><span className="eyebrow">EXECUTIVE SIGNAL</span><h3>{report.executiveSignal}</h3><p>This synthesis was generated from stored domain, item, signal, pattern, opportunity, memory, plan, and activity data.</p></div><div className="report-columns"><div><span className="eyebrow">TOP PATTERNS</span>{state.patterns.filter((pattern) => report.patternIds.includes(pattern.id)).map((pattern) => <p key={pattern.id}><strong>{pattern.name}</strong><br />{pattern.summary}</p>)}</div><div><span className="eyebrow">NEXT MOVES</span>{state.opportunities.filter((opportunity) => report.opportunityIds.includes(opportunity.id)).map((opportunity) => <p key={opportunity.id}><strong>{opportunity.title}</strong><br />{opportunity.explanation}</p>)}</div></div><div className="report-section"><span className="eyebrow">LEARNING PLAN</span>{state.plans.filter((plan) => report.planIds.includes(plan.id)).map((plan) => <div key={plan.id}>{plan.steps.map((step) => <p key={step.id}><strong>{step.order}. {step.title}</strong><br />{step.detail}</p>)}</div>)}</div><div className="report-footer">{report.acceptedMemoryIds.length} accepted memory entries · {report.activityTaskIds.length} activity records · mock mode</div></> : <div className="report-section"><button className="primary" onClick={onGenerate}>Generate Field Report</button></div>}</article> }
